/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleSplatRouteImport } from './routes/_console/$'
import { Route as ConsoleSettingsRouteImport } from './routes/_console/settings'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSplatRoute = ConsoleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof ConsoleSplatRoute
  '/settings': typeof ConsoleSettingsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/$': typeof ConsoleSplatRoute
  '/settings': typeof ConsoleSettingsRoute
  '/': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_console/$': typeof ConsoleSplatRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/$' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/$' | '/settings' | '/'
  id:
    | '__root__'
    | '/_console'
    | '/sign-in'
    | '/_console/$'
    | '/_console/settings'
    | '/_console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/$': {
      id: '/_console/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ConsoleSplatRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleSplatRoute: typeof ConsoleSplatRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleSplatRoute: ConsoleSplatRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
