/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as RelationshipRouteImport } from './routes/relationship'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WhereRouteImport } from './routes/where'
import { Route as ShellCRouteImport } from './routes/_shell/$c'
import { Route as ShellConnectRouteImport } from './routes/_shell/connect'
import { Route as ShellFeedRouteImport } from './routes/_shell/feed'
import { Route as ShellPasswordRouteImport } from './routes/_shell/password'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as ResetNewRouteImport } from './routes/reset_.new'
import { Route as ShellMHandleRouteImport } from './routes/_shell/m.$handle'
import { Route as ShellPostsIdRouteImport } from './routes/_shell/posts.$id'
import { Route as ShellConveneEventsIdRouteImport } from './routes/_shell/convene.events.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipRoute = RelationshipRouteImport.update({
  id: '/relationship',
  path: '/relationship',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereRoute = WhereRouteImport.update({
  id: '/where',
  path: '/where',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCRoute = ShellCRouteImport.update({
  id: '/$c',
  path: '/$c',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectRoute = ShellConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFeedRoute = ShellFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPasswordRoute = ShellPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => ShellRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetNewRoute = ResetNewRouteImport.update({
  id: '/reset_/new',
  path: '/reset/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellMHandleRoute = ShellMHandleRouteImport.update({
  id: '/m/$handle',
  path: '/m/$handle',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPostsIdRoute = ShellPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConveneEventsIdRoute = ShellConveneEventsIdRouteImport.update({
  id: '/convene/events/$id',
  path: '/convene/events/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/relationship': typeof RelationshipRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/welcome': typeof WelcomeRoute
  '/where': typeof WhereRoute
  '/$c': typeof ShellCRoute
  '/connect': typeof ShellConnectRoute
  '/feed': typeof ShellFeedRoute
  '/password': typeof ShellPasswordRoute
  '/e/$slug': typeof ESlugRoute
  '/reset/new': typeof ResetNewRoute
  '/m/$handle': typeof ShellMHandleRoute
  '/posts/$id': typeof ShellPostsIdRoute
  '/convene/events/$id': typeof ShellConveneEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/relationship': typeof RelationshipRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/welcome': typeof WelcomeRoute
  '/where': typeof WhereRoute
  '/$c': typeof ShellCRoute
  '/connect': typeof ShellConnectRoute
  '/feed': typeof ShellFeedRoute
  '/password': typeof ShellPasswordRoute
  '/e/$slug': typeof ESlugRoute
  '/reset/new': typeof ResetNewRoute
  '/m/$handle': typeof ShellMHandleRoute
  '/posts/$id': typeof ShellPostsIdRoute
  '/convene/events/$id': typeof ShellConveneEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/relationship': typeof RelationshipRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/welcome': typeof WelcomeRoute
  '/where': typeof WhereRoute
  '/_shell/$c': typeof ShellCRoute
  '/_shell/connect': typeof ShellConnectRoute
  '/_shell/feed': typeof ShellFeedRoute
  '/_shell/password': typeof ShellPasswordRoute
  '/e/$slug': typeof ESlugRoute
  '/reset_/new': typeof ResetNewRoute
  '/_shell/m/$handle': typeof ShellMHandleRoute
  '/_shell/posts/$id': typeof ShellPostsIdRoute
  '/_shell/convene/events/$id': typeof ShellConveneEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/relationship'
    | '/reset'
    | '/sign-in'
    | '/welcome'
    | '/where'
    | '/$c'
    | '/connect'
    | '/feed'
    | '/password'
    | '/e/$slug'
    | '/reset/new'
    | '/m/$handle'
    | '/posts/$id'
    | '/convene/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/relationship'
    | '/reset'
    | '/sign-in'
    | '/welcome'
    | '/where'
    | '/$c'
    | '/connect'
    | '/feed'
    | '/password'
    | '/e/$slug'
    | '/reset/new'
    | '/m/$handle'
    | '/posts/$id'
    | '/convene/events/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/relationship'
    | '/reset'
    | '/sign-in'
    | '/welcome'
    | '/where'
    | '/_shell/$c'
    | '/_shell/connect'
    | '/_shell/feed'
    | '/_shell/password'
    | '/e/$slug'
    | '/reset_/new'
    | '/_shell/m/$handle'
    | '/_shell/posts/$id'
    | '/_shell/convene/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  RelationshipRoute: typeof RelationshipRoute
  ResetRoute: typeof ResetRoute
  SignInRoute: typeof SignInRoute
  WelcomeRoute: typeof WelcomeRoute
  WhereRoute: typeof WhereRoute
  ESlugRoute: typeof ESlugRoute
  ResetNewRoute: typeof ResetNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship': {
      id: '/relationship'
      path: '/relationship'
      fullPath: '/relationship'
      preLoaderRoute: typeof RelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where': {
      id: '/where'
      path: '/where'
      fullPath: '/where'
      preLoaderRoute: typeof WhereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/$c': {
      id: '/_shell/$c'
      path: '/$c'
      fullPath: '/$c'
      preLoaderRoute: typeof ShellCRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connect': {
      id: '/_shell/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ShellConnectRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/feed': {
      id: '/_shell/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof ShellFeedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/password': {
      id: '/_shell/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof ShellPasswordRouteImport
      parentRoute: typeof ShellRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset_/new': {
      id: '/reset_/new'
      path: '/reset/new'
      fullPath: '/reset/new'
      preLoaderRoute: typeof ResetNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/m/$handle': {
      id: '/_shell/m/$handle'
      path: '/m/$handle'
      fullPath: '/m/$handle'
      preLoaderRoute: typeof ShellMHandleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/posts/$id': {
      id: '/_shell/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof ShellPostsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/convene/events/$id': {
      id: '/_shell/convene/events/$id'
      path: '/convene/events/$id'
      fullPath: '/convene/events/$id'
      preLoaderRoute: typeof ShellConveneEventsIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCRoute: typeof ShellCRoute
  ShellConnectRoute: typeof ShellConnectRoute
  ShellFeedRoute: typeof ShellFeedRoute
  ShellPasswordRoute: typeof ShellPasswordRoute
  ShellMHandleRoute: typeof ShellMHandleRoute
  ShellPostsIdRoute: typeof ShellPostsIdRoute
  ShellConveneEventsIdRoute: typeof ShellConveneEventsIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCRoute: ShellCRoute,
  ShellConnectRoute: ShellConnectRoute,
  ShellFeedRoute: ShellFeedRoute,
  ShellPasswordRoute: ShellPasswordRoute,
  ShellMHandleRoute: ShellMHandleRoute,
  ShellPostsIdRoute: ShellPostsIdRoute,
  ShellConveneEventsIdRoute: ShellConveneEventsIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  RelationshipRoute: RelationshipRoute,
  ResetRoute: ResetRoute,
  SignInRoute: SignInRoute,
  WelcomeRoute: WelcomeRoute,
  WhereRoute: WhereRoute,
  ESlugRoute: ESlugRoute,
  ResetNewRoute: ResetNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
