/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShellCRouteImport } from './routes/_shell/$c'
import { Route as ShellFeedRouteImport } from './routes/_shell/feed'
import { Route as ShellPostsIdRouteImport } from './routes/_shell/posts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCRoute = ShellCRouteImport.update({
  id: '/$c',
  path: '/$c',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFeedRoute = ShellFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPostsIdRoute = ShellPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/$c': typeof ShellCRoute
  '/feed': typeof ShellFeedRoute
  '/posts/$id': typeof ShellPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/$c': typeof ShellCRoute
  '/feed': typeof ShellFeedRoute
  '/posts/$id': typeof ShellPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_shell/$c': typeof ShellCRoute
  '/_shell/feed': typeof ShellFeedRoute
  '/_shell/posts/$id': typeof ShellPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/$c' | '/feed' | '/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/$c' | '/feed' | '/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/sign-in'
    | '/_shell/$c'
    | '/_shell/feed'
    | '/_shell/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/$c': {
      id: '/_shell/$c'
      path: '/$c'
      fullPath: '/$c'
      preLoaderRoute: typeof ShellCRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/feed': {
      id: '/_shell/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof ShellFeedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/posts/$id': {
      id: '/_shell/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof ShellPostsIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCRoute: typeof ShellCRoute
  ShellFeedRoute: typeof ShellFeedRoute
  ShellPostsIdRoute: typeof ShellPostsIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCRoute: ShellCRoute,
  ShellFeedRoute: ShellFeedRoute,
  ShellPostsIdRoute: ShellPostsIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
